# voici la partie 2 ou on nous demande d'écrire une documentation pour les transactions : 
#je veux, consultation du solde actuel, consultation des relevés, 

swagger: '2.0'
info:
 title: Bank Argent API documentation
 description: Contains all available API endpoints in this codebase
 version: '1.0.0'
 termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
 - http
paths:
 /transactions/current-month:
    get:
      tags:
        - Transactions
      summary: Récupérer toutes les transactions du mois en cours
      description: Retourne une liste de toutes les transactions pour le mois en cours, groupées par compte.
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        '200':
          description: Liste des transactions récupérées avec succès
          schema:
            type: object
            properties:
              transactions:
                type: array
                items:
                 $ref: '#/definitions/Transaction'
        '401':
          description: Non autorisé
        '500':
          description: Erreur interne du serveur

 /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Récupérer les détails d'une transaction
      description: Retourne les détails d'une transaction spécifique.
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/TransactionDetails'
        '404':
          description: Transaction introuvable
        '500':
          description: Erreur interne du serveur

 /transactions/{transactionId}/update:
    put:
      tags:
        - Transactions
      summary: Mettre à jour les détails d'une transaction
      description: Permet de mettre à jour les informations d'une transaction spécifique.
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Transaction mise à jour avec succès
          schema:
            $ref: '#/definitions/TransactionUpdateResponse'
        '400':
          description: Demande invalide
        '500':
          description: Erreur interne du serveur

definitions:
 Transaction:
    type: object
    properties:
      account:
        type: string
        description: Compte associé à la transaction
      transactions:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
              description: Date de la transaction
            description:
              type: string
              description: Description de la transaction
            amount:
              type: number
              description: Montant de la transaction
            balance:
              type: number
              description: Solde après la transaction

 TransactionDetails:
    type: object
    properties:
      transactionId:
        type: string
        description: ID de la transaction
      type:
        type: string
        description: Type de transaction (électronique, chèque, virement, cash)
      category:
        type: string
        description: Catégorie de la transaction
      note:
        type: string
        description: Note ajoutée par l'utilisateur

 TransactionUpdateResponse:
    type: object
    properties:
      status:
        type: string
        description: Statut de la mise à jour
      message:
        type: string
        description: Message de confirmation
